/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeDownload: typeof import('./../../src/components/CodeDownload/index.vue')['default']
    Col: typeof import('./../../src/components/Col/index.vue')['default']
    DictData: typeof import('./../../src/components/DictData/index.vue')['default']
    DictTag: typeof import('./../../src/components/DictTag/index.vue')['default']
    DownloadCode: typeof import('./../../src/components/DownloadCode/index.vue')['default']
    Editor: typeof import('./../../src/components/Editor/index.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FieldsSetting: typeof import('./../../src/components/FieldsSetting/index.vue')['default']
    FormModel: typeof import('./../../src/components/DictData/formModel.vue')['default']
    I18n: typeof import('./../../src/components/I18n/index.vue')['default']
    IconSelect: typeof import('./../../src/components/IconSelect/index.vue')['default']
    IconSvg: typeof import('./../../src/components/IconSvg/index.vue')['default']
    InnerLink: typeof import('./../../src/components/InnerLink/index.vue')['default']
    NumberAnimation: typeof import('./../../src/components/NumberAnimation/index.vue')['default']
    PageSelect: typeof import('./../../src/components/PageSelect/index.vue')['default']
    ParentView: typeof import('./../../src/components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./../../src/components/Row/index.vue')['default']
    Statistic: typeof import('./../../src/components/Statistic/index.vue')['default']
    SvgIcon: typeof import('./../../src/components/svg-icon/index.vue')['default']
    Text: typeof import('./../../src/components/Text.vue')['default']
    Tour: typeof import('./../../src/components/CodeDownload/tour.vue')['default']
    UploadImport: typeof import('./../../src/components/UploadImport/index.vue')['default']
    Watermark: typeof import('./../../src/components/Watermark/index.vue')['default']
  }
}
